# This is a basic workflow to help you get started with Actions

name: My-GitHubActions-basics
env:
  APPLICATION_NAME: "MyFlask"
  DEPLOY_PACKAGE_NAME: "flask-deploy-ver-${{ github.sha }}"
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  my-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message
        run: echo "hello world from testing"
      - name: Exec few commands
        run: |
          echo "Hello message1"
          echo "Hello message2"
          echo "Application name: ${{ env.APPLICATION_NAME }}"
      - name: List current folder
        run: ls -la

  my-deploy:
    runs-on: ubuntu-latest
    needs: [my-testing]
    steps:
      - name: Print Hello Message
        run: echo "hello world from deploy"
      - name: Exec few commands
        run: echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
